// Language file. Use as follows:
// var lg = translate.de;
// alert(lg.book); //Alerts "Speicher"
var translate = {
    us: {
        Close: "Close",
        personselect: "People",
        catselect: "Categories",
        tagselect: "Tags",
        getall: "All",
        privateselect: "Scope",
        privateprivate: "Private",
        privatepublic: "Public",
        titleapp: "WebLinks",
        Makenewweblink: "New weblink",
        editweblink: "Edit weblink",
        lblurl: "Url",
        lbltitle: "Title",
        lbldescription: "Description",
        lblcategory: "category",
        lblcategorytrash: "category (remove <b>_trash</b> to undelete)",
        lbltags: "tags",
        lblprivate: "private",
        lblrating: "rating",
        lblcreated: "created",
        lblupdated: "updated",
        About1: "About WebLinks",
        About2: "About WebLinks",
        // titleweblink: "Title",
        // textweblink: "Description",
        dueselect: "When",
        dueselecttoday: "Today",
        dueselectweek: "This week",
        dueselectmonth: "This month",
        dueselectyear: "This year",
        Favicon: "Favicon (url)",
        New: "Save+New",
        Delete: "Delete",
        Save: "Save",
        Change: "Change",
        Exit: "Exit",
        OK: "OK",
        Cancel: "Cancel",
        editweblinks: "Edit weblinks",
        closeapp: "Exit App",
        Searchfor: "Search for weblinks...",
        noinfo: "Sorry, no information available",
        reloadapp: "Reload app",
        gosettingsbox: "Settings",
        goremovebox: "Remove (menu)",
        showtrash: "Show trash",
        titletagcloud: "Tag cloud",
        hdSettings: "Settings",
        hdDownload: "Download",
        hdRemove: "Remove",
        hdShaarli: "Give settings from your Shaarli-account",
        lblsyncmethod: "Sync method",
        lblmaxload: "Maximum number of weblinks to load",
        lblmaxshow: "Number of weblinks to show (before 'show more..')",
        lbldefaultprivate: "Default private",
        msgShaarli: "Give the url and the api-secret from your Shaarli-account, so the app can synchronize with it. You can find the api-secret in the Settings/Configure menu",
        msgDownload: "Download weblinks",
        lbljsonformat: "json-format",
        lblcsvformat: "csv-format (can be imported in Excel)",
        msgRemove: "Empty trash. Remove all weblinks in trash (cannot be undone)",
        trashweblinks: "weblinks in trash",
        msg01: "WebLinks is a free program to use and manage your internet bookmarks. It's developed by Frans Schrijver, Scriptel.",
        msg04: "This program is free software: you can redistribute it and/or modify it under the terms of the GNU    General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.",
        msg05: "This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.",
        msg06: "Set secret",
        msg07: "All your data is encrypted with the following secret code. If you want to synchronize with other devices, all will have to use the same secret code. You can use this code and use it on other devices.",

    },
    nl: {
        Close: "Sluiten",
        personselect: "Wie",
        catselect: "Categorie",
        tagselect: "Tags",
        getall: "Alles",
        privateselect: "Scope",
        privateprivate: "Privé",
        privatepublic: "Publiek",
        titleapp: "WebLinks",
        Makenewweblink: "Nieuwe weblink",
        editweblink: "Bewerk weblink",
        lblurl: "Url",
        lbltitle: "Titel",
        lbldescription: "Beschrijving",
        lblcategory: "categorie",
        lblcategorytrash: "categorie (verwijder <b>_trash</b> om te herstellen)",
        lbltags: "tags",
        lblprivate: "privé",
        lblrating: "beoordeling",
        lblcreated: "gemaakt",
        lblupdated: "gewijzigd",
        About1: "Over WebLinks",
        About2: "Over WebLinks",
        // titleweblink: "Titel",
        // textweblink: "Beschrijving",
        dueselect: "Wanneer",
        dueselecttoday: "Vandaag",
        dueselectweek: "Deze week",
        dueselectmonth: "Deze maand",
        dueselectyear: "Dit jaar",
        Favicon: "Logo (url)",
        New: "Bewaar+Nieuw",
        Delete: "Wis",
        Save: "Bewaar",
        Change: "Wijzig",
        Exit: "Stop",
        OK: "OK",
        Cancel: "Annuleer",
        editweblinks: "Bewerk weblinks",
        closeapp: "App afsluiten",
        Searchfor: "Zoek weblinks...",
        noinfo: "Sorry, geen informatie beschikbaar",
        reloadapp: "App opnieuw opstarten",
        gosettingsbox: "Instellingen",
        goremovebox: "Verwijder (menu)",
        showtrash: "Prullenbak",
        titletagcloud: "Tags",
        hdSettings: "Instellingen",
        hdDownload: "Download",
        hdRemove: "Verwijder",
        hdShaarli: "Geef de instellingen van je Shaarli-account",
        lblsyncmethod: "Synchronisatiemethode",
        lblmaxload: "Maximum te laden weblinks",
        lblmaxshow: "Maximaal weer te geven (voor 'laat meer zien..')",
        lbldefaultprivate: "Standaard privé",
        msgShaarli: "Geef de url en api-secret van je Shaarli-account, zodat de app hiermee kan synchroniseren. Je vindt de api-secret in het Settings/Configure-menu van Shaarli",
        msgDownload: "Download weblinks",
        lbljsonformat: "json-formaat",
        lblcsvformat: "csv-formaat (te importeren in Excel)",
        msgRemove: "Leeg prullemand. Verwijder alle weblinks uit prullemand (kan niet ongedaan gemaakt worden)",
        trashweblinks: "weblinks in trash",
        msg01: "WebLinks is een gratis programma om weblinks te gebruiken en te beheren. WebLinks is ontwikkeld door Frans Schrijver, Scriptel.",
        msg04: "Dit programma is gratis software: je kunt deze opnieuw distribueren en/of wijzigen onder de voorwaarden van de GNU General Public License, zoals gepubliceerd door de Free Software Foundation, versie 3 van de licentie, of (naar keuze) elke latere versie.",
        msg05: "Dit programma is verspreid in de hoop dat het nuttig zal zijn, maar zonder enige garantie. Zonder zelfs de impliciete garantie van VERKOOPBAARHEID of GESCHIKTHEID VOOR EEN BEPAALD DOEL. Raadpleeg de GNU General Public License voor meer informatie.",
        msg06: "Set secret",
        msg07: "All your data is encrypted with the following secret code. If you want to synchronize with other devices, all will have to use the same secret code. You can use this code and use it on other devices.",
        msg08: "If you want to use the code from another device you can fill it in here and click Save. You can also generate a new secret by clicking new and then save. It might take some time depending on the number of weblinks",
    },
    de: {
        Close: "Close",
        personselect: "People",
        catselect: "Categories",
        tagselect: "Tags",
        getall: "Alle",
        privateselect: "Scope",
        privateprivate: "Privat",
        privatepublic: "Publik",
        titleapp: "WebLinks",
        Makenewweblink: "Neue WebLink",
        editweblink: "Edit WebLink",
        lblurl: "Url",
        lbltitle: "Title",
        lbldescription: "Description",
        lblcategory: "category",
        lblcategorytrash: "category (remove <b>_trash</b> to undelete)",
        lbltags: "tags",
        lblprivate: "private",
        lblrating: "rating",
        lblcreated: "created",
        lblupdated: "updated",
        About1: "Über WebLinks",
        About2: "Über WebLinks",
        dueselect: "Wann",
        dueselecttoday: "Heute",
        dueselectweek: "Diese Woche",
        dueselectmonth: "Dieses Monat",
        dueselectyear: "Dieses Jahr",
        Favicon: "Logo (URL)",
        New: "Speicher+Neu",
        Delete: "Löschen",
        Save: "Speicher",
        Change: "Change",
        Exit: "Exit",
        OK: "OK",
        Cancel: "Abbrechen",
        editweblinks: "Edit WebLink",
        closeapp: "Exit App",
        Searchfor: "Suche nach WebLinks ...",
        noinfo: "Sorry, keine Informationen verfügbar ",
        reloadapp: "Reload app",
        gosettingsbox: "Settings",
        goremovebox: "Remove (menu)",
        showtrash: "Show trash",
        titletagcloud: "Tag cloud",
        hdSettings: "Settings",
        hdDownload: "Download",
        hdRemove: "Remove",
        hdShaarli: "Set private names",
        lblsyncmethod: "Sync method",
        lblmaxload: "Maximum number of weblinks to load",
        lblmaxshow: "Number of weblinks to show (before 'show more..')",
        lbldefaultprivate: "Default private",
        msgShaarli: "The default private names are Home, Work and Other. Fill in your own names if you want to change this",
        msgDownload: "Download weblinks",
        lbljsonformat: "json-format",
        lblcsvformat: "csv-format (can be imported in Excel)",
        msgRemove: "Remove weblinks (cannot be undone)",
        trashweblinks: "weblinks in trash",
        msg01: "Radio weblink-to-weblink ist ein einfacher und kostenloser Internet-Radio-Player von Frans Schrijver, Scriptel.",
        msg04: "Dieses Programm ist freie Software: Sie können es verbreiten und/oder es unter den Bedingungen des GNU General Public License ändern, wie von der Free Software Foundation veröffentlicht, entweder Version 3 der Lizenz oder (nach Ihrer Wahl) jede spätere Version.",
        msg05: "Dieses Programm wird wird verteilt in der Hoffnung, dass es nützlich ist, aber ohne Garantie. Sogar ohne die implizite Gewährleistung der Marktfähigkeit oder Eignung für einen bestimmten Zweck. Lesen Sie die GNU General Public License für weitere Details.",
    }
};